variable "name" {
  description = "Identifier prefix for the instance and the resources it owns."
  type        = string
}

variable "vpc_id" {
  description = "VPC the instance is placed in."
  type        = string
}

variable "private_subnet_ids" {
  description = "Private subnets for the DB subnet group. Never pass public subnets."
  type        = list(string)

  validation {
    condition     = length(var.private_subnet_ids) >= 2
    error_message = "RDS requires a subnet group spanning at least two availability zones."
  }
}

variable "allowed_security_groups" {
  description = "Security groups permitted to open connections to Postgres, keyed by a stable name. The key identifies each rule during planning, so the group ID may only be known at apply."
  type        = map(string)
  default     = {}
}

variable "database_name" {
  description = "Name of the initial database."
  type        = string
  default     = "realworld"
}

variable "master_username" {
  description = "Master user. The password is generated by RDS into Secrets Manager and never enters Terraform state."
  type        = string
  default     = "conduit_admin"

  validation {
    condition     = !contains(["admin", "postgres", "root"], lower(var.master_username))
    error_message = "master_username must not be a reserved or well-known name."
  }
}

variable "engine_version" {
  description = "PostgreSQL engine version."
  type        = string
  default     = "16.6"
}

variable "instance_class" {
  description = "Instance class for the database."
  type        = string
  default     = "db.t4g.micro"
}

variable "allocated_storage" {
  description = "Initial storage in GiB."
  type        = number
  default     = 20
}

variable "max_allocated_storage" {
  description = "Upper bound for storage autoscaling. Set equal to allocated_storage to disable."
  type        = number
  default     = 100
}

variable "multi_az" {
  description = "Run a synchronous standby in a second availability zone."
  type        = bool
  default     = false
}

variable "backup_retention_days" {
  description = "Days of automated backups to retain. Also the point-in-time recovery window."
  type        = number
  default     = 7

  validation {
    condition     = var.backup_retention_days >= 1 && var.backup_retention_days <= 35
    error_message = "backup_retention_days must be between 1 and 35; 0 would disable point-in-time recovery."
  }
}

variable "backup_window" {
  description = "Daily backup window in UTC."
  type        = string
  default     = "03:00-04:00"
}

variable "maintenance_window" {
  description = "Weekly maintenance window in UTC. Must not overlap the backup window."
  type        = string
  default     = "sun:04:30-sun:05:30"
}

variable "deletion_protection" {
  description = "Block accidental deletion of the instance."
  type        = bool
  default     = true
}

variable "skip_final_snapshot" {
  description = "Skip the final snapshot on destroy. Leave false outside throwaway environments."
  type        = bool
  default     = false
}

variable "performance_insights_enabled" {
  description = "Enable Performance Insights."
  type        = bool
  default     = true
}

variable "monitoring_interval" {
  description = "Enhanced monitoring granularity in seconds. 0 disables it."
  type        = number
  default     = 60

  validation {
    condition     = contains([0, 1, 5, 10, 15, 30, 60], var.monitoring_interval)
    error_message = "monitoring_interval must be one of 0, 1, 5, 10, 15, 30, 60."
  }
}

variable "log_retention_days" {
  description = "Retention for the exported PostgreSQL log groups."
  type        = number
  default     = 30
}

variable "tags" {
  description = "Tags applied to every taggable resource."
  type        = map(string)
  default     = {}
}
