apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: conduit

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: conduit

resources:
  - namespace.yaml
  - configmap.yaml
  - external-secret.yaml
  - services.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - autoscaling.yaml
  - networkpolicy.yaml
  - ingress.yaml
  - migration-job.yaml
